import type { Metadata } from 'next'
import { Geist, Geist_Mono, Gugi, Open_Sans } from 'next/font/google'
import { Provider } from '../components/ui/provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const gugi = Gugi({
  variable: '--font-gugi',
  subsets: ['latin'],
  weight: '400'
})

const open = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'cowSpace',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} ${gugi.variable} ${open.variable}`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}